name: equb
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: any
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.1.0
  fancy_bottom_navigation: ^0.3.3
  flutter_fortune_wheel: ^1.2.0
  introduction_screen: ^3.0.2
  lottie: ^1.3.0
  get_storage: ^2.0.3
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  gender_picker: ^1.1.0
  connectivity_plus: ^2.3.5
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.8
  flutter_google_places: ^0.3.0
  file_picker: ^4.6.1
  intl: ^0.17.0
  google_static_maps_controller: ^1.0.0
  url_launcher: ^6.1.5
  firebase_messaging: ^11.2.8
  flutter_speed_dial: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
